# Generated by Django 4.1.2 on 2022-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_year", models.IntegerField()),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(default="", max_length=100)),
                ("rejection_percentage", models.CharField(max_length=10)),
                ("reason_1", models.CharField(max_length=100)),
                ("reason_2", models.CharField(max_length=100)),
                ("reason_3", models.CharField(max_length=100)),
            ],
        ),
    ]
